# Each template: (title, description, warmup, main_activity, cooldown, safety_tip, estimated_minutes)
GOAL_TEMPLATES = {
    "Lose Weight": [
        (
            "Walking",
            "Steady beginner walk to build daily movement habit and light calorie burn.",
            "March in place and ankle circles for 5 minutes.",
            "20-minute brisk walk at a conversational pace.",
            "Hamstring, calf, and hip flexor stretches for 5 minutes.",
            "Keep posture tall and breathe through your nose when possible.",
            25,
        ),
        (
            "Light Cardio",
            "Low-impact cardio to raise heart rate without joint stress.",
            "Dynamic warm-up: arm swings and gentle side steps for 5 minutes.",
            "15 minutes step-touch + 5 minutes light marching intervals.",
            "Slow walk and deep breathing cooldown for 5 minutes.",
            "Stay at a pace where you can still speak in short sentences.",
            25,
        ),
        (
            "Low-Impact HIIT",
            "Short work/rest intervals designed for beginners.",
            "Joint mobility: hips, knees, and shoulders for 5 minutes.",
            "8 rounds of 20 seconds step jacks + 40 seconds rest.",
            "Walking cooldown and stretching for 5 minutes.",
            "Stop if dizzy and sip water between rounds.",
            20,
        ),
        (
            "Bodyweight Movement",
            "Simple strength and movement patterns to support fat loss.",
            "March and torso rotations for 5 minutes.",
            "2 rounds: 10 air squats, 8 knee push-ups, 12 standing crunches.",
            "Full-body stretch flow for 5 minutes.",
            "Move with control; quality beats speed.",
            28,
        ),
        (
            "Active Recovery",
            "Easy recovery day to stay consistent without overtraining.",
            "Gentle shoulder and hip circles for 3 minutes.",
            "20-minute relaxed walk outdoors or indoors.",
            "Long holds for calves, quads, and lower back.",
            "Recovery days help you stay on track long term.",
            20,
        ),
    ],
    "Gain Muscle": [
        (
            "Squats",
            "Foundational lower-body strength for beginners.",
            "Leg swings and hip circles for 5 minutes.",
            "3 sets of 10 bodyweight squats with 60 seconds rest between sets.",
            "Quad and glute stretches for 5 minutes.",
            "Keep knees aligned with toes and chest lifted.",
            28,
        ),
        (
            "Wall Push-Ups",
            "Beginner upper-body pushing strength.",
            "Arm circles and wall slides for 5 minutes.",
            "3 sets of 8–12 wall push-ups with controlled tempo.",
            "Chest and shoulder stretches for 5 minutes.",
            "Keep core tight and avoid sagging hips.",
            25,
        ),
        (
            "Lunges",
            "Single-leg strength and balance basics.",
            "March in place and ankle mobility for 5 minutes.",
            "3 sets of 8 reverse lunges per leg.",
            "Hip flexor and hamstring stretch for 5 minutes.",
            "Use a chair for balance if needed.",
            30,
        ),
        (
            "Glute Bridge",
            "Posterior chain activation for stable strength gains.",
            "Cat-cow and hip openers for 5 minutes.",
            "3 sets of 12 glute bridges with 2-second squeeze at top.",
            "Figure-four stretch and supine twists.",
            "Press through heels, not lower back.",
            24,
        ),
        (
            "Core Stability",
            "Beginner core work for posture and strength support.",
            "Dead bug prep and breathing drills for 5 minutes.",
            "Plank 20s, bird-dog 8/side, dead bug 8/side — repeat 2 rounds.",
            "Child pose and lower-back decompression.",
            "Breathe steadily; stop if lower back pinches.",
            22,
        ),
        (
            "Recovery Mobility",
            "Light movement day to support muscle recovery.",
            "Easy full-body mobility flow for 5 minutes.",
            "10-minute walk + gentle flexibility routine.",
            "Long static stretches for tight areas.",
            "Muscles adapt during recovery, not only during work.",
            20,
        ),
    ],
    "Improve Endurance": [
        (
            "Walking Intervals",
            "Build aerobic base with structured walk intervals.",
            "March and calf raises for 5 minutes.",
            "6 rounds: 2 minutes brisk walk + 1 minute easy walk.",
            "Slow walk and calf stretch cooldown.",
            "Maintain steady breathing throughout.",
            28,
        ),
        (
            "Jogging Intervals",
            "Introduce light jogging with walk recovery.",
            "Brisk walk warm-up for 5 minutes.",
            "7 rounds: 1 minute light jog + 2 minutes walk.",
            "Easy walk and hip flexor stretches.",
            "Jog effort should feel easy, not a sprint.",
            30,
        ),
        (
            "Breathing Exercises",
            "Breath control to support endurance and recovery.",
            "Light march and posture reset for 5 minutes.",
            "Box breathing 4-4-4-4 for 5 minutes + 15-minute steady walk.",
            "Diaphragmatic breathing cooldown.",
            "Inhale through nose, exhale slowly through mouth.",
            22,
        ),
        (
            "Gradual Time Increase",
            "Progress session length safely week by week.",
            "Dynamic mobility warm-up for 5 minutes.",
            "25-minute steady cardio (walk or light jog) at consistent pace.",
            "Gradual cooldown walk and stretching.",
            "Increase duration before increasing intensity.",
            32,
        ),
    ],
    "Improve Flexibility": [
        (
            "Stretching",
            "Full-body beginner stretch routine.",
            "Light march and joint circles for 3 minutes.",
            "Hamstring, hip, shoulder, and chest stretches — 30s each.",
            "Relaxed breathing in comfortable positions.",
            "Move into stretch slowly; no bouncing.",
            20,
        ),
        (
            "Mobility",
            "Joint mobility drills for daily movement quality.",
            "Cat-cow and shoulder rolls for 3 minutes.",
            "Hip circles, thoracic rotations, and ankle mobility sequence.",
            "Supine twists and gentle neck mobility.",
            "Stay within pain-free range of motion.",
            18,
        ),
        (
            "Yoga-Inspired Beginner Exercises",
            "Simple yoga-style flow for flexibility and calm.",
            "Sun-breath and mountain pose prep for 3 minutes.",
            "Mountain, forward fold, low lunge, child pose — 2 slow rounds.",
            "Guided breathing in seated position.",
            "Stability first; depth second.",
            22,
        ),
        (
            "Relaxation and Recovery",
            "Recovery-focused flexibility and breath work.",
            "Neck and shoulder release for 3 minutes.",
            "Gentle full-body mobility and long stretch holds.",
            "5-minute quiet breathing session.",
            "Relax jaw and shoulders; avoid tension.",
            16,
        ),
    ],
    "General Fitness": [
        (
            "Mix of Cardio",
            "Balanced cardio session for overall fitness.",
            "March and mobility warm-up for 5 minutes.",
            "15 minutes light cardio + 5 minutes step-touch intervals.",
            "Walking cooldown and stretch.",
            "Keep posture upright and land softly.",
            28,
        ),
        (
            "Strength",
            "Beginner strength circuit for whole-body fitness.",
            "Dynamic warm-up for 5 minutes.",
            "2 rounds: squats, wall push-ups, lunges, plank (30s).",
            "Mobility cooldown for 5 minutes.",
            "Control every repetition.",
            30,
        ),
        (
            "Flexibility",
            "Mobility and stretch day within a balanced plan.",
            "Joint prep and arm circles for 4 minutes.",
            "Full-body stretch sequence with 30-second holds.",
            "Breathing-focused cooldown.",
            "Use support for balance if needed.",
            22,
        ),
        (
            "Core",
            "Core stability for posture and daily movement.",
            "Torso activation and cat-cow for 4 minutes.",
            "Plank, dead bug, and bird-dog circuit — 2 rounds.",
            "Lower-back friendly stretches.",
            "Stop if you feel strain in the lower back.",
            25,
        ),
        (
            "Recovery",
            "Active recovery to maintain consistency.",
            "Easy movement prep for 3 minutes.",
            "Relaxed walk and light flexibility work.",
            "Long cooldown holds and deep breathing.",
            "Recovery is part of sustainable progress.",
            20,
        ),
    ],
}
